project:
  type: book
  output-dir: docs

book:
  title: "R for Household Consumption and Expenditure Surveys"
  subtitle: "Nutrition Data Analysis"
  author: "Liberty Mlambo,Lucia Sergovia de la Revilla, Thomas Codd, Louise E. Ander"
  date: "16/10/2023"
  repo-url: https://github.com/dzvoti/mapsNutritionR/
  repo-actions: [edit]
  # downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    # - intro.qmd
    - 1_introR.qmd
    # - 1_data_types.qmd
    - data_structures.qmd
    # - 1_data_wrangling_and_io.qmd
    # - 2_hcesNutR.qmd
    # - 3_fct.qmd
    # - 4_food-matching.qmd
    # - summary.qmd
    # - references.qmd
  sidebar:
    tools:
      - icon: cloud-arrow-down
        href: https://dzvoti.github.io/hces4R/hces-datazip
        aria-label: Download data

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 1
    toc-title: "On this page"
  pdf:
    documentclass: scrreprt

editor: source

# Do not evaluate code chunks
eval: false
callout-icon: false



